### ISSUE TITLE
Keep semantic versioning standards

### ISSUE THREAD

**Issue by Martodox** [mydea/ember-date-components#16]
Hey,
This is not an issue per say, but a request for the maintainers.
Since this is an ember addon with 1,821 downloads in the last month, please, use semantic versioning as it is supposed to be used.

v.1.1.0  should have been released as v2.0.0 since it brought "[POTENTIALLY BREAKING]" changes, which actually broke some of our builds :D

👍 +1 for keeping the changelog nice and clean.

If you need someone to keep the semantic versioning in check, let me know - I am more than happy to help out :)

**Comment by mydea** [comment]
Yes, I have also noticed that later on in one of our apps - sorry about that. It is actually a bug, since the thing that broke it shouldn't have - I thought I've written it in a way to handle this.

I'll release a patch that should hopefully fix this issue. The 'breaking' should have only be a potential if using the interact helper in a very weird way.

**Comment by mydea** [comment]
This should hopefully be fixed in v1.1.2!
